name: NickName
version: '1.0-SNAPSHOT'
main: org.mcodin5569.nickName.NickName
api-version: '1.20'
commands:
  nick:
    description: Ändert deinen Nickname
    usage: /nick <Name>
    permission: nickname.change